---
- name: Install and configure Ansible.
  hosts: factory

  tasks:
    # This is necessary when connecting to the managed node with an SSH password
    # that is used from the inventory file.
    - name: Enable noninteractive SSH password authentication
      become: yes
      ansible.builtin.apt:
        package: sshpass
        state: present

    - name: Add abbreviations for Ansible commands
      vars:
        fish_abbreviations_to_add:
          a: ansible
          ap: ansible-playbook
          agx: ansible-galaxy
          mol: molecule
      ansible.builtin.include_tasks: ../tasks/fish_add_abbreviations.yml

    - name: Install Ansible packages into the main Python virtual environment.
      ansible.builtin.shell:
        executable: "{{ werkstatt_fish_path }}"
        cmd: |
          vf activate main
          pip install {{ item }}
        creates: ~/.virtualenvs/main/bin/{{ item }}
      loop:
        - ansible
        - ansible-lint
        - molecule
